analyzer:
  errors:
    prefer_single_quotes: ignore
    unused_import: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false  # Uncomment to disable the avoid_print rule
    prefer_single_quotes: true  # Uncomment to enable the prefer_single_quotes rule
