name: ekramproject
description: "A new Flutter project."
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  google_maps_flutter: ^2.6.1 
  curved_navigation_bar: ^1.0.3
  url_launcher: ^6.0.12
  file_picker: ^8.0.3
  flutter_polyline_points: ^2.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  intl: ^0.17.0

 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_intl:
  enabled: true
